#line 1 "D:\\win_flex_bison-latest\\code.yy.c"

#line 3 "D:\\win_flex_bison-latest\\code.yy.c"

#define  YY_INT_ALIGNED short int

/* A lexical scanner generated by flex */

#define FLEX_SCANNER
#define YY_FLEX_MAJOR_VERSION 2
#define YY_FLEX_MINOR_VERSION 6
#define YY_FLEX_SUBMINOR_VERSION 4
#if YY_FLEX_SUBMINOR_VERSION > 0
#define FLEX_BETA
#endif

/* First, we deal with  platform-specific or compiler-specific issues. */

/* begin standard C headers. */
#include <stdio.h>
#include <string.h>
#include <errno.h>
#include <stdlib.h>

/* end standard C headers. */

/* flex integer type definitions */

#ifndef FLEXINT_H
#define FLEXINT_H

/* C99 systems have <inttypes.h>. Non-C99 systems may or may not. */

#if defined (__STDC_VERSION__) && __STDC_VERSION__ >= 199901L

/* C99 says to define __STDC_LIMIT_MACROS before including stdint.h,
 * if you want the limit (max/min) macros for int types. 
 */
#ifndef __STDC_LIMIT_MACROS
#define __STDC_LIMIT_MACROS 1
#endif

#include <inttypes.h>
typedef int8_t flex_int8_t;
typedef uint8_t flex_uint8_t;
typedef int16_t flex_int16_t;
typedef uint16_t flex_uint16_t;
typedef int32_t flex_int32_t;
typedef uint32_t flex_uint32_t;
#else
typedef signed char flex_int8_t;
typedef short int flex_int16_t;
typedef int flex_int32_t;
typedef unsigned char flex_uint8_t; 
typedef unsigned short int flex_uint16_t;
typedef unsigned int flex_uint32_t;

/* Limits of integral types. */
#ifndef INT8_MIN
#define INT8_MIN               (-128)
#endif
#ifndef INT16_MIN
#define INT16_MIN              (-32767-1)
#endif
#ifndef INT32_MIN
#define INT32_MIN              (-2147483647-1)
#endif
#ifndef INT8_MAX
#define INT8_MAX               (127)
#endif
#ifndef INT16_MAX
#define INT16_MAX              (32767)
#endif
#ifndef INT32_MAX
#define INT32_MAX              (2147483647)
#endif
#ifndef UINT8_MAX
#define UINT8_MAX              (255U)
#endif
#ifndef UINT16_MAX
#define UINT16_MAX             (65535U)
#endif
#ifndef UINT32_MAX
#define UINT32_MAX             (4294967295U)
#endif

#ifndef SIZE_MAX
#define SIZE_MAX               (~(size_t)0)
#endif

#endif /* ! C99 */

#endif /* ! FLEXINT_H */

/* begin standard C++ headers. */

/* TODO: this is always defined, so inline it */
#define yyconst const

#if defined(__GNUC__) && __GNUC__ >= 3
#define yynoreturn __attribute__((__noreturn__))
#else
#define yynoreturn
#endif

/* Returned upon end-of-file. */
#define YY_NULL 0

/* Promotes a possibly negative, possibly signed char to an
 *   integer in range [0..255] for use as an array index.
 */
#define YY_SC_TO_UI(c) ((YY_CHAR) (c))

/* Enter a start condition.  This macro really ought to take a parameter,
 * but we do it the disgusting crufty way forced on us by the ()-less
 * definition of BEGIN.
 */
#define BEGIN (yy_start) = 1 + 2 *
/* Translate the current start state into a value that can be later handed
 * to BEGIN to return to the state.  The YYSTATE alias is for lex
 * compatibility.
 */
#define YY_START (((yy_start) - 1) / 2)
#define YYSTATE YY_START
/* Action number for EOF rule of a given start state. */
#define YY_STATE_EOF(state) (YY_END_OF_BUFFER + state + 1)
/* Special action meaning "start processing a new file". */
#define YY_NEW_FILE yyrestart( yyin  )
#define YY_END_OF_BUFFER_CHAR 0

/* Size of default input buffer. */
#ifndef YY_BUF_SIZE
#ifdef __ia64__
/* On IA-64, the buffer size is 16k, not 8k.
 * Moreover, YY_BUF_SIZE is 2*YY_READ_BUF_SIZE in the general case.
 * Ditto for the __ia64__ case accordingly.
 */
#define YY_BUF_SIZE 32768
#else
#define YY_BUF_SIZE 16384
#endif /* __ia64__ */
#endif

/* The state buf must be large enough to hold one state per character in the main buffer.
 */
#define YY_STATE_BUF_SIZE   ((YY_BUF_SIZE + 2) * sizeof(yy_state_type))

#ifndef YY_TYPEDEF_YY_BUFFER_STATE
#define YY_TYPEDEF_YY_BUFFER_STATE
typedef struct yy_buffer_state *YY_BUFFER_STATE;
#endif

#ifndef YY_TYPEDEF_YY_SIZE_T
#define YY_TYPEDEF_YY_SIZE_T
typedef size_t yy_size_t;
#endif

extern int yyleng;

extern FILE *yyin, *yyout;

#define EOB_ACT_CONTINUE_SCAN 0
#define EOB_ACT_END_OF_FILE 1
#define EOB_ACT_LAST_MATCH 2
    
    #define YY_LESS_LINENO(n)
    #define YY_LINENO_REWIND_TO(ptr)
    
/* Return all but the first "n" matched characters back to the input stream. */
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
        int yyless_macro_arg = (n); \
        YY_LESS_LINENO(yyless_macro_arg);\
		*yy_cp = (yy_hold_char); \
		YY_RESTORE_YY_MORE_OFFSET \
		(yy_c_buf_p) = yy_cp = yy_bp + yyless_macro_arg - YY_MORE_ADJ; \
		YY_DO_BEFORE_ACTION; /* set up yytext again */ \
		} \
	while ( 0 )
#define unput(c) yyunput( c, (yytext_ptr)  )

#ifndef YY_STRUCT_YY_BUFFER_STATE
#define YY_STRUCT_YY_BUFFER_STATE
struct yy_buffer_state
	{
	FILE *yy_input_file;

	char *yy_ch_buf;		/* input buffer */
	char *yy_buf_pos;		/* current position in input buffer */

	/* Size of input buffer in bytes, not including room for EOB
	 * characters.
	 */
	int yy_buf_size;

	/* Number of characters read into yy_ch_buf, not including EOB
	 * characters.
	 */
	int yy_n_chars;

	/* Whether we "own" the buffer - i.e., we know we created it,
	 * and can realloc() it to grow it, and should free() it to
	 * delete it.
	 */
	int yy_is_our_buffer;

	/* Whether this is an "interactive" input source; if so, and
	 * if we're using stdio for input, then we want to use getc()
	 * instead of fread(), to make sure we stop fetching input after
	 * each newline.
	 */
	int yy_is_interactive;

	/* Whether we're considered to be at the beginning of a line.
	 * If so, '^' rules will be active on the next match, otherwise
	 * not.
	 */
	int yy_at_bol;

    int yy_bs_lineno; /**< The line count. */
    int yy_bs_column; /**< The column count. */

	/* Whether to try to fill the input buffer when we reach the
	 * end of it.
	 */
	int yy_fill_buffer;

	int yy_buffer_status;

#define YY_BUFFER_NEW 0
#define YY_BUFFER_NORMAL 1
	/* When an EOF's been seen but there's still some text to process
	 * then we mark the buffer as YY_EOF_PENDING, to indicate that we
	 * shouldn't try reading from the input source any more.  We might
	 * still have a bunch of tokens to match, though, because of
	 * possible backing-up.
	 *
	 * When we actually see the EOF, we change the status to "new"
	 * (via yyrestart()), so that the user can continue scanning by
	 * just pointing yyin at a new input file.
	 */
#define YY_BUFFER_EOF_PENDING 2

	};
#endif /* !YY_STRUCT_YY_BUFFER_STATE */

/* Stack of input buffers. */
static size_t yy_buffer_stack_top = 0; /**< index of top of stack. */
static size_t yy_buffer_stack_max = 0; /**< capacity of stack. */
static YY_BUFFER_STATE * yy_buffer_stack = NULL; /**< Stack as an array. */

/* We provide macros for accessing buffer states in case in the
 * future we want to put the buffer states in a more general
 * "scanner state".
 *
 * Returns the top of the stack, or NULL.
 */
#define YY_CURRENT_BUFFER ( (yy_buffer_stack) \
                          ? (yy_buffer_stack)[(yy_buffer_stack_top)] \
                          : NULL)
/* Same as previous macro, but useful when we know that the buffer stack is not
 * NULL or when we need an lvalue. For internal use only.
 */
#define YY_CURRENT_BUFFER_LVALUE (yy_buffer_stack)[(yy_buffer_stack_top)]

/* yy_hold_char holds the character lost when yytext is formed. */
static char yy_hold_char;
static int yy_n_chars;		/* number of characters read into yy_ch_buf */
int yyleng;

/* Points to current character in buffer. */
static char *yy_c_buf_p = NULL;
static int yy_init = 0;		/* whether we need to initialize */
static int yy_start = 0;	/* start state number */

/* Flag which is used to allow yywrap()'s to do buffer switches
 * instead of setting up a fresh yyin.  A bit of a hack ...
 */
static int yy_did_buffer_switch_on_eof;

void yyrestart ( FILE *input_file  );
void yy_switch_to_buffer ( YY_BUFFER_STATE new_buffer  );
YY_BUFFER_STATE yy_create_buffer ( FILE *file, int size  );
void yy_delete_buffer ( YY_BUFFER_STATE b  );
void yy_flush_buffer ( YY_BUFFER_STATE b  );
void yypush_buffer_state ( YY_BUFFER_STATE new_buffer  );
void yypop_buffer_state ( void );

static void yyensure_buffer_stack ( void );
static void yy_load_buffer_state ( void );
static void yy_init_buffer ( YY_BUFFER_STATE b, FILE *file  );
#define YY_FLUSH_BUFFER yy_flush_buffer( YY_CURRENT_BUFFER )

YY_BUFFER_STATE yy_scan_buffer ( char *base, yy_size_t size  );
YY_BUFFER_STATE yy_scan_string ( const char *yy_str  );
YY_BUFFER_STATE yy_scan_bytes ( const char *bytes, int len  );

void *yyalloc ( yy_size_t  );
void *yyrealloc ( void *, yy_size_t  );
void yyfree ( void *  );

#define yy_new_buffer yy_create_buffer
#define yy_set_interactive(is_interactive) \
	{ \
	if ( ! YY_CURRENT_BUFFER ){ \
        yyensure_buffer_stack (); \
		YY_CURRENT_BUFFER_LVALUE =    \
            yy_create_buffer( yyin, YY_BUF_SIZE ); \
	} \
	YY_CURRENT_BUFFER_LVALUE->yy_is_interactive = is_interactive; \
	}
#define yy_set_bol(at_bol) \
	{ \
	if ( ! YY_CURRENT_BUFFER ){\
        yyensure_buffer_stack (); \
		YY_CURRENT_BUFFER_LVALUE =    \
            yy_create_buffer( yyin, YY_BUF_SIZE ); \
	} \
	YY_CURRENT_BUFFER_LVALUE->yy_at_bol = at_bol; \
	}
#define YY_AT_BOL() (YY_CURRENT_BUFFER_LVALUE->yy_at_bol)

/* Begin user sect3 */

#define yywrap() (/*CONSTCOND*/1)
#define YY_SKIP_YYWRAP
typedef flex_uint8_t YY_CHAR;

FILE *yyin = NULL, *yyout = NULL;

typedef int yy_state_type;

extern int yylineno;
int yylineno = 1;

extern char *yytext;
#ifdef yytext_ptr
#undef yytext_ptr
#endif
#define yytext_ptr yytext

static yy_state_type yy_get_previous_state ( void );
static yy_state_type yy_try_NUL_trans ( yy_state_type current_state  );
static int yy_get_next_buffer ( void );
static void yynoreturn yy_fatal_error ( const char* msg  );

/* Done after the current pattern has been matched and before the
 * corresponding action - sets up yytext.
 */
#define YY_DO_BEFORE_ACTION \
	(yytext_ptr) = yy_bp; \
	yyleng = (int) (yy_cp - yy_bp); \
	(yy_hold_char) = *yy_cp; \
	*yy_cp = '\0'; \
	(yy_c_buf_p) = yy_cp;
#define YY_NUM_RULES 113
#define YY_END_OF_BUFFER 114
/* This struct is not used in this scanner,
   but its presence is necessary. */
struct yy_trans_info
	{
	flex_int32_t yy_verify;
	flex_int32_t yy_nxt;
	};
static const flex_int16_t yy_accept[416] =
    {   0,
        0,    0,  114,  112,    5,    1,   98,  111,  112,  104,
       97,  112,   92,   93,  102,  101,   89,  100,   96,  103,
       55,   54,   90,   86,  105,   91,  106,  109,   52,   52,
       94,   95,  107,   52,   52,   52,   52,   52,   52,   52,
       52,   52,   52,   52,   52,   52,   52,   52,   52,   87,
      108,   88,   99,   85,  111,  111,   63,    0,    4,   71,
       88,   80,   72,    0,    0,   69,   77,   67,   78,   68,
       79,    0,   58,    2,    3,   70,   59,   55,  110,  110,
      110,   55,   55,  110,   55,   54,   54,   54,   54,   95,
       87,   94,   76,   82,   84,   83,   75,   52,  111,    0,

       73,   52,   52,   52,   52,   52,   52,   52,   52,   52,
       52,   52,   52,   52,   52,   52,   13,   52,   52,   52,
       52,   52,   52,   21,   52,   52,   52,   52,   52,   52,
       52,   52,   52,   52,   52,   52,   74,   81,   63,    0,
        0,    0,  111,    0,   56,    0,    0,   64,    0,   58,
        3,   58,  110,   59,    0,   57,   55,   55,   55,   55,
      110,   53,   54,   54,   54,   54,   66,   65,   52,   52,
       52,   52,   52,   52,   52,   52,   52,   52,   52,   52,
       52,   52,   52,   52,   52,   52,   52,   52,   52,   52,
       19,   52,   52,   23,   52,   52,   52,   52,   52,   52,

       52,   52,   52,   52,   52,   52,   52,   52,   52,   52,
        0,    0,  111,  111,    0,    0,    0,   58,  110,   58,
        0,   59,   57,   57,   55,  110,  110,   53,  110,   53,
       53,   54,   52,   52,   52,   52,   52,   52,   52,   52,
       52,   52,   52,    6,   52,    8,    9,   52,   52,   52,
       52,   15,   16,   52,   52,   20,   52,   24,   52,   52,
       52,   52,   52,   52,   52,   52,   52,   52,   52,   52,
       37,   52,   52,    0,    0,  111,  111,    0,    0,   58,
       59,   57,  110,  110,   53,   53,    0,   60,   53,   53,
       52,   52,   43,   52,   52,   52,   52,   52,   52,   52,

       52,    7,   10,   52,   52,   52,   52,   18,   52,   52,
       52,   52,   28,   52,   52,   52,   52,   52,   52,   35,
       52,   52,   39,    0,    0,   59,    0,   61,    0,   62,
       60,   60,   53,   52,   52,   52,   52,   52,   52,   52,
       52,   52,   52,   52,   52,   14,   17,   22,   52,   52,
       27,   29,   30,   31,   32,   33,   52,   52,   52,    0,
        0,   61,   61,   62,   62,   60,   52,   52,   42,   52,
       52,   52,   47,   52,   52,   52,   52,   52,   12,   52,
       52,   34,   52,   52,   61,   62,   40,   41,   44,   45,
       52,   52,   52,   52,   51,   11,   25,   26,   36,   38,

       52,   48,   52,   52,   46,   52,   52,   52,   52,   52,
       52,   52,   50,   49,    0
    } ;

static const YY_CHAR yy_ec[256] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    2,    3,
        2,    2,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    2,    4,    5,    6,    1,    7,    8,    9,   10,
       11,   12,   13,   14,   15,   16,   17,   18,   19,   19,
       19,   19,   19,   19,   19,   20,   21,   22,   23,   24,
       25,   26,   27,    1,   28,   29,   30,   31,   32,   33,
       34,   35,   36,   35,   35,   37,   35,   38,   35,   39,
       35,   35,   40,   41,   42,   35,   35,   43,   35,   35,
       44,   45,   46,   47,   48,    1,   49,   50,   51,   52,

       53,   54,   55,   56,   57,   35,   58,   59,   60,   61,
       62,   63,   35,   64,   65,   66,   67,   68,   69,   70,
       71,   72,   73,   74,   75,   76,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,

        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1
    } ;

static const YY_CHAR yy_meta[77] =
    {   0,
        1,    1,    2,    1,    3,    1,    1,    1,    4,    1,
        1,    1,    1,    1,    1,    5,    1,    6,    6,    7,
        7,    1,    1,    1,    1,    1,    4,    7,    7,    7,
        7,    7,    7,    8,    8,    8,    8,    8,    8,    8,
        8,    8,    8,    1,    4,    1,    1,    8,    6,    6,
        7,    7,    7,    6,    8,    8,    8,    8,    8,    8,
        9,    8,    8,    9,    8,    9,    8,    9,    8,    9,
        8,    8,    1,    1,    1,    1
    } ;

static const flex_int16_t yy_base[429] =
    {   0,
        0,    0,  841,  842,  842,  842,  815,   75,    0,   53,
       73,  794,  842,  842,  813,   69,  842,   70,   68,   80,
      105,   90,  811,  842,   92,  811,   65,  842,    0,   95,
      842,  842,  810,  125,  767,  769,   79,   40,   42,   56,
      770,   75,  769,  777,  111,  758,  125,  766,  771,  842,
       82,  842,  842,  842,  169,  174,  176,  120,    0,  842,
      842,  842,  842,   74,  132,  842,  842,  842,  842,  842,
      842,  810,  173,  842,    0,  842,  202,  210,  180,    0,
      244,  174,  103,  262,  128,    0,  200,  123,  207,  842,
      842,  842,  800,  842,  842,  842,  799,    0,  243,  778,

      842,  138,  757,  756,  763,  123,  740,  727,  734,  735,
      721,  730,  717,  731,  701,  707,  685,  678,  673,  673,
      676,  673,  669,    0,  149,  673,  185,  671,   97,   82,
      675,  668,  725,  152,  179,  672,  842,  842,  266,  180,
      723,  183,  282,    0,  215,  280,    0,  842,  311,  842,
        0,  285,  322,    0,  286,  327,  212,    0,  690,  667,
      369,  312,  230,    0,  688,  665,  842,  842,  666,  660,
      659,  660,  656,  667,  655,  647,  661,  645,  641,  644,
      656,  651,  635,  210,  649,  647,  642,  634,  640,  642,
        0,  627,  631,    0,  632,  628,  618,  616,  618,  620,

      623,  609,  596,  596,  607,  596,  600,  604,  606,  595,
      241,  291,  348,  422,  350,  468,  337,  411,  390,    0,
      364,  394,  472,    0,    0,  257,  313,  391,  514,  333,
      397,    0,  598,  592,  592,  587,  590,  586,  583,  586,
      567,  579,  570,    0,  572,    0,    0,  563,  571,  552,
      559,    0,    0,  553,  550,    0,  553,    0,  548,  548,
      547,  544,  556,  546,  550,  555,  553,  551,  541,  545,
        0,  533,  544,  461,    0,  372,    0,  276,    0,  518,
      524,  842,  545,  555,  349,    0,  416,  561,  559,  536,
      532,  535,    0,  532,  526,  528,  523,  505,  512,  518,

      511,    0,    0,  498,  497,  501,  492,    0,  499,  484,
      484,  479,    0,  478,  474,  474,  458,  467,  463,    0,
      454,  457,    0,  463,  616,  842,  441,  568,  528,  605,
      653,    0,    0,  274,  461,  458,  453,  446,  451,  436,
      451,  443,  446,  418,  418,    0,    0,    0,  430,  427,
        0,    0,    0,    0,    0,    0,  415,  410,  398,  401,
        0,  659,    0,  682,    0,  842,  384,  391,    0,  368,
      374,  358,    0,  340,  348,  346,  332,  325,    0,  309,
      306,    0,  313,  310,  842,  842,    0,    0,    0,    0,
      298,  273,  270,  243,    0,    0,    0,    0,    0,    0,

      202,    0,  205,  196,    0,  188,  193,  154,  140,   80,
       74,   47,    0,    0,  842,  741,  750,  759,  764,  768,
      775,  782,  791,  800,  804,  806,  811,  815
    } ;

static const flex_int16_t yy_def[429] =
    {   0,
      415,    1,  415,  415,  415,  415,  415,  416,  417,  415,
      415,  418,  415,  415,  415,  415,  415,  415,  415,  415,
      419,  419,  415,  415,  415,  415,  415,  415,  420,  420,
      415,  415,  415,  420,  420,  420,  420,  420,  420,  420,
      420,  420,  420,  420,  420,  420,  420,  420,  420,  415,
      415,  415,  415,  415,  416,  416,  415,  421,  417,  415,
      415,  415,  415,  418,  422,  415,  415,  415,  415,  415,
      415,  415,  415,  415,  423,  415,  419,   22,  419,  419,
      419,  419,  419,  419,  419,   22,  419,  419,  419,  415,
      415,  415,  415,  415,  415,  415,  415,  420,  416,  418,

      415,  420,  420,  420,  420,  420,  420,  420,  420,  420,
      420,  420,  420,  420,  420,  420,  420,  420,  420,  420,
      420,  420,  420,  420,  420,  420,  420,  420,  420,  420,
      420,  420,  420,  420,  420,  420,  415,  415,  415,  424,
      415,  415,  416,  425,  418,  418,  426,  415,  415,  415,
      423,   77,  419,  419,  415,  419,  419,  419,  419,  419,
      419,   84,  419,  419,  419,  419,  415,  415,  420,  420,
      420,  420,  420,  420,  420,  420,  420,  420,  420,  420,
      420,  420,  420,  420,  420,  420,  420,  420,  420,  420,
      420,  420,  420,  420,  420,  420,  420,  420,  420,  420,

      420,  420,  420,  420,  420,  420,  420,  420,  420,  420,
      424,  427,  416,  416,  418,  418,  415,  415,  419,  419,
      415,   77,  415,  419,  419,  161,  161,  419,  419,  419,
      419,  419,  420,  420,  420,  420,  420,  420,  420,  420,
      420,  420,  420,  420,  420,  420,  420,  420,  420,  420,
      420,  420,  420,  420,  420,  420,  420,  420,  420,  420,
      420,  420,  420,  420,  420,  420,  420,  420,  420,  420,
      420,  420,  420,  424,  428,  416,  214,  418,  216,  419,
      415,  415,  419,  419,  419,  419,  415,  419,  419,  419,
      420,  420,  420,  420,  420,  420,  420,  420,  420,  420,

      420,  420,  420,  420,  420,  420,  420,  420,  420,  420,
      420,  420,  420,  420,  420,  420,  420,  420,  420,  420,
      420,  420,  420,  424,  424,  415,  415,  419,  415,  419,
      415,  419,  419,  420,  420,  420,  420,  420,  420,  420,
      420,  420,  420,  420,  420,  420,  420,  420,  420,  420,
      420,  420,  420,  420,  420,  420,  420,  420,  420,  424,
      325,  415,  419,  415,  419,  415,  420,  420,  420,  420,
      420,  420,  420,  420,  420,  420,  420,  420,  420,  420,
      420,  420,  420,  420,  415,  415,  420,  420,  420,  420,
      420,  420,  420,  420,  420,  420,  420,  420,  420,  420,

      420,  420,  420,  420,  420,  420,  420,  420,  420,  420,
      420,  420,  420,  420,    0,  415,  415,  415,  415,  415,
      415,  415,  415,  415,  415,  415,  415,  415
    } ;

static const flex_int16_t yy_nxt[919] =
    {   0,
        4,    5,    6,    7,    8,    9,   10,   11,   12,   13,
       14,   15,   16,   17,   18,   19,   20,   21,   22,   22,
       22,   23,   24,   25,   26,   27,   28,   29,   29,   29,
       29,   29,   29,   29,   29,   29,   30,   29,   29,   29,
       29,   30,   29,   31,    4,   32,   33,   34,   35,   36,
       37,   38,   39,   40,   41,   29,   42,   29,   43,   29,
       29,   29,   29,   44,   45,   46,   47,   48,   49,   29,
       29,   29,   50,   51,   52,   53,   56,   60,   61,   57,
       62,   67,  145,   72,   69,   73,   73,   73,   73,   96,
       97,   74,  116,   68,   70,   71,   75,   63,   91,   99,

      118,  117,  119,  100,   76,   77,  137,   86,   86,   86,
       86,  120,  414,   92,  121,   93,   94,  122,   65,   58,
       77,   81,   78,   78,   79,   79,   87,  113,  124,   99,
      202,   88,  413,  100,  114,  125,   81,  143,  143,  159,
      115,   82,   81,  412,  133,  203,   83,   84,   89,  146,
      146,  200,  102,  103,  104,  138,   88,   81,  105,  165,
      106,  160,  107,   85,  108,  109,  128,  129,  201,  158,
       56,   83,  110,   57,   84,   56,  130,  139,   57,  131,
      140,  166,  174,  175,   57,  134,  157,  140,  411,  144,
       73,   73,   73,   73,  158,   77,  169,   79,   79,   79,

       79,  147,  141,  170,  149,  150,  410,  193,  206,  150,
      157,   81,  141,   58,  194,  158,  207,  141,   58,  152,
      152,  152,  152,  145,  212,  149,  150,   78,   78,   79,
       79,  150,   81,  153,  154,  208,  163,  209,  154,  196,
      158,  164,  142,  409,   56,   57,   82,   57,  164,  197,
      198,   83,  408,  158,  153,  154,  155,  407,  155,   65,
      154,  156,  156,  156,  156,  163,  164,  139,   85,  406,
      140,  164,  405,  164,  248,  249,   83,  161,  158,  162,
      162,  162,  162,   56,  145,  212,   57,   58,  145,  162,
      162,  162,  162,  162,  162,  283,  164,  215,  215,  213,

      213,  404,  141,  223,  223,  223,  223,  141,  274,  274,
      162,  162,  162,  162,  162,  162,  219,  220,  403,  283,
       65,  220,  367,  217,   65,  217,   58,  227,  218,  218,
      218,  218,  142,  402,  221,  368,  221,  219,  220,  222,
      222,  222,  222,  220,  156,  156,  156,  156,  228,   56,
      229,  284,   57,  230,  218,  218,  218,  218,  145,  224,
      275,  401,  400,  224,  399,  276,  276,  278,  278,  289,
      231,  398,  397,   56,  229,  284,   57,  396,  230,  395,
      224,  281,  281,  281,  281,  224,  226,  226,  226,  226,
      286,  290,   58,  394,   65,  393,  226,  226,  226,  226,

      226,  226,  217,  392,  217,   57,  391,  280,  280,  280,
      280,  222,  222,  222,  222,  286,   58,  226,  226,  226,
      226,  226,  226,   56,  390,   80,   57,  285,  218,  218,
      218,  218,  286,  331,  331,  331,  331,  389,  286,  277,
      277,  277,  277,  150,  388,  212,   80,  150,  387,  277,
      277,  277,  277,  277,  277,  285,  384,  286,  362,  362,
      362,  362,  383,  286,  150,   57,   58,   57,  382,  150,
      277,  277,  277,  277,  277,  277,  145,  381,  324,  324,
      360,  360,  380,  379,  378,  279,  279,  279,  279,  223,
      223,  223,  223,  377,  376,  279,  279,  279,  279,  279,

      279,  375,  374,  373,  282,  212,  372,  212,  282,  371,
      370,  369,   65,  359,  358,  357,  279,  279,  279,  279,
      279,  279,  356,  355,  354,  282,  287,  353,  287,  352,
      282,  288,  288,  288,  288,  280,  280,  280,  280,  351,
      350,  281,  281,  281,  281,  364,  364,  364,  364,  349,
      220,  348,  347,  346,  220,  345,  326,  327,  344,  327,
      326,  343,  328,  328,  328,  328,  342,  329,  341,  329,
      340,  220,  330,  330,  330,  330,  220,  326,  288,  288,
      288,  288,  326,  339,  338,  328,  328,  328,  328,  337,
      336,  335,  334,  332,  333,  333,  323,  332,  322,  321,

      363,  320,  319,  318,  363,  317,  316,  315,  314,  313,
      312,  311,  310,  309,  332,  308,  307,  306,  305,  332,
       57,  363,  330,  330,  330,  330,  363,  304,  303,  302,
      301,  300,  299,  361,  361,  361,  361,  365,  298,  297,
      296,  365,  295,  361,  361,  361,  361,  361,  361,  294,
      293,  292,  291,  273,  272,  271,  270,  269,  365,  268,
      212,  267,  266,  365,  361,  361,  361,  361,  361,  361,
      331,  331,  331,  331,  265,  264,  362,  362,  362,  362,
      263,  262,  261,  260,  259,  366,  258,  257,  256,  366,
      255,  385,  254,  253,  252,  385,  251,  250,  247,  364,

      364,  364,  364,  246,  245,  244,  366,  243,  242,  241,
      240,  366,  385,  239,  386,  238,  237,  385,  386,  236,
      235,  234,  233,  232,  232,  225,  225,  140,  210,   99,
      205,  204,  199,  195,  192,  386,  191,  190,  189,  188,
      386,   55,  187,   55,   55,   55,   55,   55,   55,   55,
       59,  186,   59,   59,   59,   59,   59,   59,   59,   64,
      185,  184,   64,   64,   64,   64,   64,   64,   80,   80,
       80,   80,   80,   98,   98,   98,   98,   55,   55,  183,
       55,  182,  181,   55,   64,   64,  180,   64,  179,  178,
       64,  151,  177,  151,  151,  151,  151,  151,  151,  151,

      211,  176,  211,  211,  211,  211,  211,  211,  211,  214,
      214,  216,  216,  211,  211,  173,  211,  172,  171,  211,
      325,  325,   65,  168,  167,  148,  136,  135,  132,  127,
      126,  123,  112,  111,  101,   95,   90,   66,   65,   54,
      415,    3,  415,  415,  415,  415,  415,  415,  415,  415,
      415,  415,  415,  415,  415,  415,  415,  415,  415,  415,
      415,  415,  415,  415,  415,  415,  415,  415,  415,  415,
      415,  415,  415,  415,  415,  415,  415,  415,  415,  415,
      415,  415,  415,  415,  415,  415,  415,  415,  415,  415,
      415,  415,  415,  415,  415,  415,  415,  415,  415,  415,

      415,  415,  415,  415,  415,  415,  415,  415,  415,  415,
      415,  415,  415,  415,  415,  415,  415,  415
    } ;

static const flex_int16_t yy_chk[919] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    8,   10,   10,    8,
       11,   16,   64,   19,   18,   19,   19,   19,   19,   27,
       27,   20,   38,   16,   18,   18,   20,   11,   25,   30,

       39,   38,   39,   30,   20,   22,   51,   22,   22,   22,
       22,   39,  412,   25,   40,   25,   25,   40,   64,    8,
       21,   22,   21,   21,   21,   21,   22,   37,   42,   47,
      130,   22,  411,   47,   37,   42,   21,   58,   58,   83,
       37,   21,   22,  410,   47,  130,   21,   21,   22,   65,
       65,  129,   34,   34,   34,   51,   22,   21,   34,   88,
       34,   83,   34,   21,   34,   34,   45,   45,  129,   85,
       55,   21,   34,   55,   21,   56,   45,   57,   56,   45,
       57,   88,  106,  106,  140,   47,   85,  142,  409,   58,
       73,   73,   73,   73,   85,   79,  102,   79,   79,   79,

       79,   65,  142,  102,   73,   73,  408,  125,  134,   73,
       82,   79,   57,   55,  125,   82,  134,   57,   56,   77,
       77,   77,   77,  145,  140,   73,   73,   78,   78,   78,
       78,   73,   79,   77,   77,  135,   87,  135,   77,  127,
       82,   87,   57,  407,   99,  211,   78,   99,   89,  127,
      127,   78,  406,  157,   77,   77,   81,  404,   81,  145,
       77,   81,   81,   81,   81,   89,   87,  139,   78,  403,
      139,  163,  401,   89,  184,  184,   78,   84,  157,   84,
       84,   84,   84,  143,  278,  211,  143,   99,  146,   84,
       84,   84,   84,   84,   84,  226,  163,  146,  146,  143,

      143,  394,  139,  155,  155,  155,  155,  139,  212,  212,
       84,   84,   84,   84,   84,   84,  152,  152,  393,  226,
      278,  152,  334,  149,  146,  149,  143,  162,  149,  149,
      149,  149,  139,  392,  153,  334,  153,  152,  152,  153,
      153,  153,  153,  152,  156,  156,  156,  156,  162,  213,
      162,  227,  213,  162,  217,  217,  217,  217,  215,  156,
      212,  391,  384,  156,  383,  213,  213,  215,  215,  230,
      162,  381,  380,  276,  162,  227,  276,  378,  162,  377,
      156,  221,  221,  221,  221,  156,  161,  161,  161,  161,
      285,  230,  213,  376,  215,  375,  161,  161,  161,  161,

      161,  161,  219,  374,  219,  360,  372,  219,  219,  219,
      219,  222,  222,  222,  222,  285,  276,  161,  161,  161,
      161,  161,  161,  214,  371,  222,  214,  228,  218,  218,
      218,  218,  228,  287,  287,  287,  287,  370,  231,  214,
      214,  214,  214,  218,  368,  360,  222,  218,  367,  214,
      214,  214,  214,  214,  214,  231,  359,  228,  327,  327,
      327,  327,  358,  231,  218,  274,  214,  324,  357,  218,
      214,  214,  214,  214,  214,  214,  216,  350,  274,  274,
      324,  324,  349,  345,  344,  216,  216,  216,  216,  223,
      223,  223,  223,  343,  342,  216,  216,  216,  216,  216,

      216,  341,  340,  339,  223,  274,  338,  324,  223,  337,
      336,  335,  216,  322,  321,  319,  216,  216,  216,  216,
      216,  216,  318,  317,  316,  223,  229,  315,  229,  314,
      223,  229,  229,  229,  229,  280,  280,  280,  280,  312,
      311,  281,  281,  281,  281,  329,  329,  329,  329,  310,
      280,  309,  307,  306,  280,  305,  281,  283,  304,  283,
      281,  301,  283,  283,  283,  283,  300,  284,  299,  284,
      298,  280,  284,  284,  284,  284,  280,  281,  288,  288,
      288,  288,  281,  297,  296,  328,  328,  328,  328,  295,
      294,  292,  291,  288,  290,  289,  273,  288,  272,  270,

      328,  269,  268,  267,  328,  266,  265,  264,  263,  262,
      261,  260,  259,  257,  288,  255,  254,  251,  250,  288,
      325,  328,  330,  330,  330,  330,  328,  249,  248,  245,
      243,  242,  241,  325,  325,  325,  325,  330,  240,  239,
      238,  330,  237,  325,  325,  325,  325,  325,  325,  236,
      235,  234,  233,  210,  209,  208,  207,  206,  330,  205,
      325,  204,  203,  330,  325,  325,  325,  325,  325,  325,
      331,  331,  331,  331,  202,  201,  362,  362,  362,  362,
      200,  199,  198,  197,  196,  331,  195,  193,  192,  331,
      190,  362,  189,  188,  187,  362,  186,  185,  183,  364,

      364,  364,  364,  182,  181,  180,  331,  179,  178,  177,
      176,  331,  362,  175,  364,  174,  173,  362,  364,  172,
      171,  170,  169,  166,  165,  160,  159,  141,  136,  133,
      132,  131,  128,  126,  123,  364,  122,  121,  120,  119,
      364,  416,  118,  416,  416,  416,  416,  416,  416,  416,
      417,  117,  417,  417,  417,  417,  417,  417,  417,  418,
      116,  115,  418,  418,  418,  418,  418,  418,  419,  419,
      419,  419,  419,  420,  420,  420,  420,  421,  421,  114,
      421,  113,  112,  421,  422,  422,  111,  422,  110,  109,
      422,  423,  108,  423,  423,  423,  423,  423,  423,  423,

      424,  107,  424,  424,  424,  424,  424,  424,  424,  425,
      425,  426,  426,  427,  427,  105,  427,  104,  103,  427,
      428,  428,  100,   97,   93,   72,   49,   48,   46,   44,
       43,   41,   36,   35,   33,   26,   23,   15,   12,    7,
        3,  415,  415,  415,  415,  415,  415,  415,  415,  415,
      415,  415,  415,  415,  415,  415,  415,  415,  415,  415,
      415,  415,  415,  415,  415,  415,  415,  415,  415,  415,
      415,  415,  415,  415,  415,  415,  415,  415,  415,  415,
      415,  415,  415,  415,  415,  415,  415,  415,  415,  415,
      415,  415,  415,  415,  415,  415,  415,  415,  415,  415,

      415,  415,  415,  415,  415,  415,  415,  415,  415,  415,
      415,  415,  415,  415,  415,  415,  415,  415
    } ;

static yy_state_type yy_last_accepting_state;
static char *yy_last_accepting_cpos;

extern int yy_flex_debug;
int yy_flex_debug = 0;

/* The intent behind this definition is that it'll catch
 * any uses of REJECT which flex missed.
 */
#define REJECT reject_used_but_not_detected
#define yymore() yymore_used_but_not_detected
#define YY_MORE_ADJ 0
#define YY_RESTORE_YY_MORE_OFFSET
char *yytext;
#line 1 "D:\\win_flex_bison-latest\\code.l"
/*
 * c11.lex: An C11 scanner
 * 
 */
/* do not wrap */
/* Some useful grammar */
#line 28 "D:\\win_flex_bison-latest\\code.l"
#include <stdio.h>

/* C token types */
#define KEYWORD 1
#define IDENTIFIER 2
#define I_CONSTANT 3 // integer constant
#define F_CONSTANT 4 // floating constant
#define C_CONSTANT 5 // character constant
#define STRING_LITERAL 6
#define PUNCTUATOR 7

/* statistics */
int charCount = 0;
int lineCount = 1;
int columnCount = 1;
int keywordCount = 0;
int identifierCount = 0;
int integerConst = 0;
int floatingConst = 0;
int charConst = 0;
int stringCount = 0;
int punctuatorCount = 0;
int errorCount = 0;

/* handle errors */
void yyerror(const char *);

/* handle multi-line comments */
static void isComment(void);
#line 824 "D:\\win_flex_bison-latest\\code.yy.c"
#line 825 "D:\\win_flex_bison-latest\\code.yy.c"

#define INITIAL 0

/*windows compatibility case*/
#include <io.h>
#define isatty _isatty
#define fileno _fileno
    
#ifndef YY_EXTRA_TYPE
#define YY_EXTRA_TYPE void *
#endif

static int yy_init_globals ( void );

/* Accessor methods to globals.
   These are made visible to non-reentrant scanners for convenience. */

int yylex_destroy ( void );

int yyget_debug ( void );

void yyset_debug ( int debug_flag  );

YY_EXTRA_TYPE yyget_extra ( void );

void yyset_extra ( YY_EXTRA_TYPE user_defined  );

FILE *yyget_in ( void );

void yyset_in  ( FILE * _in_str  );

FILE *yyget_out ( void );

void yyset_out  ( FILE * _out_str  );

			int yyget_leng ( void );

char *yyget_text ( void );

int yyget_lineno ( void );

void yyset_lineno ( int _line_number  );

/* Macros after this point can all be overridden by user definitions in
 * section 1.
 */

#ifndef YY_SKIP_YYWRAP
#ifdef __cplusplus
extern "C" int yywrap ( void );
#else
extern int yywrap ( void );
#endif
#endif

#ifndef YY_NO_UNPUT
    
    static void yyunput ( int c, char *buf_ptr  );
    
#endif

#ifndef yytext_ptr
static void yy_flex_strncpy ( char *, const char *, int );
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen ( const char * );
#endif

#ifndef YY_NO_INPUT
#ifdef __cplusplus
static int yyinput ( void );
#else
static int input ( void );
#endif

#endif

/* Amount of stuff to slurp up with each read. */
#ifndef YY_READ_BUF_SIZE
#ifdef __ia64__
/* On IA-64, the buffer size is 16k, not 8k */
#define YY_READ_BUF_SIZE 16384
#else
#define YY_READ_BUF_SIZE 8192
#endif /* __ia64__ */
#endif

/* Copy whatever the last rule matched to the standard output. */
#ifndef ECHO
/* This used to be an fputs(), but since the string might contain NUL's,
 * we now use fwrite().
 */
#define ECHO do { if (fwrite( yytext, (size_t) yyleng, 1, yyout )) {} } while (0)
#endif

/* Gets input and stuffs it into "buf".  number of characters read, or YY_NULL,
 * is returned in "result".
 */
#ifndef YY_INPUT
#define YY_INPUT(buf,result,max_size) \
	if ( YY_CURRENT_BUFFER_LVALUE->yy_is_interactive ) \
		{ \
		int c = '*'; \
		int n; \
		for ( n = 0; n < max_size && \
			     (c = getc( yyin )) != EOF && c != '\n'; ++n ) \
			buf[n] = (char) c; \
		if ( c == '\n' ) \
			buf[n++] = (char) c; \
		if ( c == EOF && ferror( yyin ) ) \
			YY_FATAL_ERROR( "input in flex scanner failed" ); \
		result = n; \
		} \
	else \
		{ \
		errno=0; \
		while ( (result = (int) fread(buf, 1, (yy_size_t) max_size, yyin)) == 0 && ferror(yyin)) \
			{ \
			if( errno != EINTR) \
				{ \
				YY_FATAL_ERROR( "input in flex scanner failed" ); \
				break; \
				} \
			errno=0; \
			clearerr(yyin); \
			} \
		}\
\

#endif

/* No semi-colon after return; correct usage is to write "yyterminate();" -
 * we don't want an extra ';' after the "return" because that will cause
 * some compilers to complain about unreachable statements.
 */
#ifndef yyterminate
#define yyterminate() return YY_NULL
#endif

/* Number of entries by which start-condition stack grows. */
#ifndef YY_START_STACK_INCR
#define YY_START_STACK_INCR 25
#endif

/* Report a fatal error. */
#ifndef YY_FATAL_ERROR
#define YY_FATAL_ERROR(msg) yy_fatal_error( msg )
#endif

/* end tables serialization structures and prototypes */

/* Default declaration of generated scanner - a define so the user can
 * easily add parameters.
 */
#ifndef YY_DECL
#define YY_DECL_IS_OURS 1

extern int yylex (void);

#define YY_DECL int yylex (void)
#endif /* !YY_DECL */

/* Code executed at the beginning of each rule, after yytext and yyleng
 * have been set up.
 */
#ifndef YY_USER_ACTION
#define YY_USER_ACTION
#endif

/* Code executed at the end of each rule. */
#ifndef YY_BREAK
#define YY_BREAK /*LINTED*/break;
#endif

#define YY_RULE_SETUP \
	YY_USER_ACTION

/** The main scanner function which does all the work.
 */
YY_DECL
{
	yy_state_type yy_current_state;
	char *yy_cp, *yy_bp;
	int yy_act;
    
	if ( !(yy_init) )
		{
		(yy_init) = 1;

#ifdef YY_USER_INIT
		YY_USER_INIT;
#endif

		if ( ! (yy_start) )
			(yy_start) = 1;	/* first start state */

		if ( ! yyin )
			yyin = stdin;

		if ( ! yyout )
			yyout = stdout;

		if ( ! YY_CURRENT_BUFFER ) {
			yyensure_buffer_stack ();
			YY_CURRENT_BUFFER_LVALUE =
				yy_create_buffer( yyin, YY_BUF_SIZE );
		}

		yy_load_buffer_state(  );
		}

	{
#line 59 "D:\\win_flex_bison-latest\\code.l"

#line 1041 "D:\\win_flex_bison-latest\\code.yy.c"

	while ( /*CONSTCOND*/1 )		/* loops until end-of-file is reached */
		{
		yy_cp = (yy_c_buf_p);

		/* Support of yytext. */
		*yy_cp = (yy_hold_char);

		/* yy_bp points to the position in yy_ch_buf of the start of
		 * the current run.
		 */
		yy_bp = yy_cp;

		yy_current_state = (yy_start);
yy_match:
		do
			{
			YY_CHAR yy_c = yy_ec[YY_SC_TO_UI(*yy_cp)] ;
			if ( yy_accept[yy_current_state] )
				{
				(yy_last_accepting_state) = yy_current_state;
				(yy_last_accepting_cpos) = yy_cp;
				}
			while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
				{
				yy_current_state = (int) yy_def[yy_current_state];
				if ( yy_current_state >= 416 )
					yy_c = yy_meta[yy_c];
				}
			yy_current_state = yy_nxt[yy_base[yy_current_state] + yy_c];
			++yy_cp;
			}
		while ( yy_base[yy_current_state] != 842 );

yy_find_action:
		yy_act = yy_accept[yy_current_state];
		if ( yy_act == 0 )
			{ /* have to back up */
			yy_cp = (yy_last_accepting_cpos);
			yy_current_state = (yy_last_accepting_state);
			yy_act = yy_accept[yy_current_state];
			}

		YY_DO_BEFORE_ACTION;

do_action:	/* This label is used only to access EOF actions. */

		switch ( yy_act )
	{ /* beginning of action switch */
			case 0: /* must back up */
			/* undo the effects of YY_DO_BEFORE_ACTION */
			*yy_cp = (yy_hold_char);
			yy_cp = (yy_last_accepting_cpos);
			yy_current_state = (yy_last_accepting_state);
			goto yy_find_action;

case 1:
/* rule 1 can match eol */
YY_RULE_SETUP
#line 60 "D:\\win_flex_bison-latest\\code.l"
{ lineCount++; columnCount=0; return -1; } /* wrap */
	YY_BREAK
case 2:
YY_RULE_SETUP
#line 61 "D:\\win_flex_bison-latest\\code.l"
{ isComment(); return -1; }   /* multi-line comment begins */
	YY_BREAK
case 3:
YY_RULE_SETUP
#line 62 "D:\\win_flex_bison-latest\\code.l"
{ return -1; }  /* single-line comment */
	YY_BREAK
case 4:
YY_RULE_SETUP
#line 63 "D:\\win_flex_bison-latest\\code.l"
{ return -1; }  /* preprocessor directive */
	YY_BREAK
case 5:
YY_RULE_SETUP
#line 64 "D:\\win_flex_bison-latest\\code.l"
{return -1;}    /* white space */
	YY_BREAK
case 6:
YY_RULE_SETUP
#line 66 "D:\\win_flex_bison-latest\\code.l"
{ return KEYWORD; } /* keywords */
	YY_BREAK
case 7:
YY_RULE_SETUP
#line 67 "D:\\win_flex_bison-latest\\code.l"
{ return KEYWORD; }
	YY_BREAK
case 8:
YY_RULE_SETUP
#line 68 "D:\\win_flex_bison-latest\\code.l"
{ return KEYWORD; }
	YY_BREAK
case 9:
YY_RULE_SETUP
#line 69 "D:\\win_flex_bison-latest\\code.l"
{ return KEYWORD; }
	YY_BREAK
case 10:
YY_RULE_SETUP
#line 70 "D:\\win_flex_bison-latest\\code.l"
{ return KEYWORD; }
	YY_BREAK
case 11:
YY_RULE_SETUP
#line 71 "D:\\win_flex_bison-latest\\code.l"
{ return KEYWORD; }
	YY_BREAK
case 12:
YY_RULE_SETUP
#line 72 "D:\\win_flex_bison-latest\\code.l"
{ return KEYWORD; }
	YY_BREAK
case 13:
YY_RULE_SETUP
#line 73 "D:\\win_flex_bison-latest\\code.l"
{ return KEYWORD; }
	YY_BREAK
case 14:
YY_RULE_SETUP
#line 74 "D:\\win_flex_bison-latest\\code.l"
{ return KEYWORD; }
	YY_BREAK
case 15:
YY_RULE_SETUP
#line 75 "D:\\win_flex_bison-latest\\code.l"
{ return KEYWORD; }
	YY_BREAK
case 16:
YY_RULE_SETUP
#line 76 "D:\\win_flex_bison-latest\\code.l"
{ return KEYWORD; }
	YY_BREAK
case 17:
YY_RULE_SETUP
#line 77 "D:\\win_flex_bison-latest\\code.l"
{ return KEYWORD; }
	YY_BREAK
case 18:
YY_RULE_SETUP
#line 78 "D:\\win_flex_bison-latest\\code.l"
{ return KEYWORD; }
	YY_BREAK
case 19:
YY_RULE_SETUP
#line 79 "D:\\win_flex_bison-latest\\code.l"
{ return KEYWORD; }
	YY_BREAK
case 20:
YY_RULE_SETUP
#line 80 "D:\\win_flex_bison-latest\\code.l"
{ return KEYWORD; }
	YY_BREAK
case 21:
YY_RULE_SETUP
#line 81 "D:\\win_flex_bison-latest\\code.l"
{ return KEYWORD; }
	YY_BREAK
case 22:
YY_RULE_SETUP
#line 82 "D:\\win_flex_bison-latest\\code.l"
{ return KEYWORD; }
	YY_BREAK
case 23:
YY_RULE_SETUP
#line 83 "D:\\win_flex_bison-latest\\code.l"
{ return KEYWORD; }
	YY_BREAK
case 24:
YY_RULE_SETUP
#line 84 "D:\\win_flex_bison-latest\\code.l"
{ return KEYWORD; }
	YY_BREAK
case 25:
YY_RULE_SETUP
#line 85 "D:\\win_flex_bison-latest\\code.l"
{ return KEYWORD; }
	YY_BREAK
case 26:
YY_RULE_SETUP
#line 86 "D:\\win_flex_bison-latest\\code.l"
{ return KEYWORD; }
	YY_BREAK
case 27:
YY_RULE_SETUP
#line 87 "D:\\win_flex_bison-latest\\code.l"
{ return KEYWORD; }
	YY_BREAK
case 28:
YY_RULE_SETUP
#line 88 "D:\\win_flex_bison-latest\\code.l"
{ return KEYWORD; }
	YY_BREAK
case 29:
YY_RULE_SETUP
#line 89 "D:\\win_flex_bison-latest\\code.l"
{ return KEYWORD; }
	YY_BREAK
case 30:
YY_RULE_SETUP
#line 90 "D:\\win_flex_bison-latest\\code.l"
{ return KEYWORD; }
	YY_BREAK
case 31:
YY_RULE_SETUP
#line 91 "D:\\win_flex_bison-latest\\code.l"
{ return KEYWORD; }
	YY_BREAK
case 32:
YY_RULE_SETUP
#line 92 "D:\\win_flex_bison-latest\\code.l"
{ return KEYWORD; }
	YY_BREAK
case 33:
YY_RULE_SETUP
#line 93 "D:\\win_flex_bison-latest\\code.l"
{ return KEYWORD; }
	YY_BREAK
case 34:
YY_RULE_SETUP
#line 94 "D:\\win_flex_bison-latest\\code.l"
{ return KEYWORD; }
	YY_BREAK
case 35:
YY_RULE_SETUP
#line 95 "D:\\win_flex_bison-latest\\code.l"
{ return KEYWORD; }
	YY_BREAK
case 36:
YY_RULE_SETUP
#line 96 "D:\\win_flex_bison-latest\\code.l"
{ return KEYWORD; }
	YY_BREAK
case 37:
YY_RULE_SETUP
#line 97 "D:\\win_flex_bison-latest\\code.l"
{ return KEYWORD; }
	YY_BREAK
case 38:
YY_RULE_SETUP
#line 98 "D:\\win_flex_bison-latest\\code.l"
{ return KEYWORD; }
	YY_BREAK
case 39:
YY_RULE_SETUP
#line 99 "D:\\win_flex_bison-latest\\code.l"
{ return KEYWORD; }
	YY_BREAK
case 40:
YY_RULE_SETUP
#line 100 "D:\\win_flex_bison-latest\\code.l"
{ return KEYWORD; }
	YY_BREAK
case 41:
YY_RULE_SETUP
#line 101 "D:\\win_flex_bison-latest\\code.l"
{ return KEYWORD; }
	YY_BREAK
case 42:
YY_RULE_SETUP
#line 102 "D:\\win_flex_bison-latest\\code.l"
{ return KEYWORD; }
	YY_BREAK
case 43:
YY_RULE_SETUP
#line 103 "D:\\win_flex_bison-latest\\code.l"
{ return KEYWORD; }
	YY_BREAK
case 44:
YY_RULE_SETUP
#line 104 "D:\\win_flex_bison-latest\\code.l"
{ return KEYWORD; }
	YY_BREAK
case 45:
YY_RULE_SETUP
#line 105 "D:\\win_flex_bison-latest\\code.l"
{ return KEYWORD; }
	YY_BREAK
case 46:
YY_RULE_SETUP
#line 106 "D:\\win_flex_bison-latest\\code.l"
{ return KEYWORD; }
	YY_BREAK
case 47:
YY_RULE_SETUP
#line 107 "D:\\win_flex_bison-latest\\code.l"
{ return KEYWORD; }
	YY_BREAK
case 48:
YY_RULE_SETUP
#line 108 "D:\\win_flex_bison-latest\\code.l"
{ return KEYWORD; }
	YY_BREAK
case 49:
YY_RULE_SETUP
#line 109 "D:\\win_flex_bison-latest\\code.l"
{ return KEYWORD; }
	YY_BREAK
case 50:
YY_RULE_SETUP
#line 110 "D:\\win_flex_bison-latest\\code.l"
{ return KEYWORD; }
	YY_BREAK
case 51:
YY_RULE_SETUP
#line 111 "D:\\win_flex_bison-latest\\code.l"
{ return KEYWORD; }
	YY_BREAK
case 52:
YY_RULE_SETUP
#line 113 "D:\\win_flex_bison-latest\\code.l"
{ return IDENTIFIER; }  /* identifiers */
	YY_BREAK
case 53:
YY_RULE_SETUP
#line 115 "D:\\win_flex_bison-latest\\code.l"
{ return I_CONSTANT; }  /* constants */
	YY_BREAK
case 54:
YY_RULE_SETUP
#line 116 "D:\\win_flex_bison-latest\\code.l"
{ return I_CONSTANT; }
	YY_BREAK
case 55:
YY_RULE_SETUP
#line 117 "D:\\win_flex_bison-latest\\code.l"
{ return I_CONSTANT; }
	YY_BREAK
case 56:
YY_RULE_SETUP
#line 118 "D:\\win_flex_bison-latest\\code.l"
{ return C_CONSTANT; }
	YY_BREAK
case 57:
YY_RULE_SETUP
#line 120 "D:\\win_flex_bison-latest\\code.l"
{ return F_CONSTANT; }
	YY_BREAK
case 58:
YY_RULE_SETUP
#line 121 "D:\\win_flex_bison-latest\\code.l"
{ return F_CONSTANT; }
	YY_BREAK
case 59:
YY_RULE_SETUP
#line 122 "D:\\win_flex_bison-latest\\code.l"
{ return F_CONSTANT; }
	YY_BREAK
case 60:
YY_RULE_SETUP
#line 123 "D:\\win_flex_bison-latest\\code.l"
{ return F_CONSTANT; }
	YY_BREAK
case 61:
YY_RULE_SETUP
#line 124 "D:\\win_flex_bison-latest\\code.l"
{ return F_CONSTANT; }
	YY_BREAK
case 62:
YY_RULE_SETUP
#line 125 "D:\\win_flex_bison-latest\\code.l"
{ return F_CONSTANT; }
	YY_BREAK
case 63:
YY_RULE_SETUP
#line 127 "D:\\win_flex_bison-latest\\code.l"
{ return STRING_LITERAL; }  /* strings literal */
	YY_BREAK
case 64:
YY_RULE_SETUP
#line 131 "D:\\win_flex_bison-latest\\code.l"
{ return PUNCTUATOR; }  /* punctuators */
	YY_BREAK
case 65:
YY_RULE_SETUP
#line 132 "D:\\win_flex_bison-latest\\code.l"
{ return PUNCTUATOR; }
	YY_BREAK
case 66:
YY_RULE_SETUP
#line 133 "D:\\win_flex_bison-latest\\code.l"
{ return PUNCTUATOR; }
	YY_BREAK
case 67:
YY_RULE_SETUP
#line 134 "D:\\win_flex_bison-latest\\code.l"
{ return PUNCTUATOR; }
	YY_BREAK
case 68:
YY_RULE_SETUP
#line 135 "D:\\win_flex_bison-latest\\code.l"
{ return PUNCTUATOR; }
	YY_BREAK
case 69:
YY_RULE_SETUP
#line 136 "D:\\win_flex_bison-latest\\code.l"
{ return PUNCTUATOR; }
	YY_BREAK
case 70:
YY_RULE_SETUP
#line 137 "D:\\win_flex_bison-latest\\code.l"
{ return PUNCTUATOR; }
	YY_BREAK
case 71:
YY_RULE_SETUP
#line 138 "D:\\win_flex_bison-latest\\code.l"
{ return PUNCTUATOR; }
	YY_BREAK
case 72:
YY_RULE_SETUP
#line 139 "D:\\win_flex_bison-latest\\code.l"
{ return PUNCTUATOR; }
	YY_BREAK
case 73:
YY_RULE_SETUP
#line 140 "D:\\win_flex_bison-latest\\code.l"
{ return PUNCTUATOR; }
	YY_BREAK
case 74:
YY_RULE_SETUP
#line 141 "D:\\win_flex_bison-latest\\code.l"
{ return PUNCTUATOR; }
	YY_BREAK
case 75:
YY_RULE_SETUP
#line 142 "D:\\win_flex_bison-latest\\code.l"
{ return PUNCTUATOR; }
	YY_BREAK
case 76:
YY_RULE_SETUP
#line 143 "D:\\win_flex_bison-latest\\code.l"
{ return PUNCTUATOR; }
	YY_BREAK
case 77:
YY_RULE_SETUP
#line 144 "D:\\win_flex_bison-latest\\code.l"
{ return PUNCTUATOR; }
	YY_BREAK
case 78:
YY_RULE_SETUP
#line 145 "D:\\win_flex_bison-latest\\code.l"
{ return PUNCTUATOR; }
	YY_BREAK
case 79:
YY_RULE_SETUP
#line 146 "D:\\win_flex_bison-latest\\code.l"
{ return PUNCTUATOR; }
	YY_BREAK
case 80:
YY_RULE_SETUP
#line 147 "D:\\win_flex_bison-latest\\code.l"
{ return PUNCTUATOR; }
	YY_BREAK
case 81:
YY_RULE_SETUP
#line 148 "D:\\win_flex_bison-latest\\code.l"
{ return PUNCTUATOR; }
	YY_BREAK
case 82:
YY_RULE_SETUP
#line 149 "D:\\win_flex_bison-latest\\code.l"
{ return PUNCTUATOR; }
	YY_BREAK
case 83:
YY_RULE_SETUP
#line 150 "D:\\win_flex_bison-latest\\code.l"
{ return PUNCTUATOR; }
	YY_BREAK
case 84:
YY_RULE_SETUP
#line 151 "D:\\win_flex_bison-latest\\code.l"
{ return PUNCTUATOR; }
	YY_BREAK
case 85:
YY_RULE_SETUP
#line 152 "D:\\win_flex_bison-latest\\code.l"
{ return PUNCTUATOR; }
	YY_BREAK
case 86:
YY_RULE_SETUP
#line 153 "D:\\win_flex_bison-latest\\code.l"
{ return PUNCTUATOR; }
	YY_BREAK
case 87:
YY_RULE_SETUP
#line 154 "D:\\win_flex_bison-latest\\code.l"
{ return PUNCTUATOR; }
	YY_BREAK
case 88:
YY_RULE_SETUP
#line 155 "D:\\win_flex_bison-latest\\code.l"
{ return PUNCTUATOR; }
	YY_BREAK
case 89:
YY_RULE_SETUP
#line 156 "D:\\win_flex_bison-latest\\code.l"
{ return PUNCTUATOR; }
	YY_BREAK
case 90:
YY_RULE_SETUP
#line 157 "D:\\win_flex_bison-latest\\code.l"
{ return PUNCTUATOR; }
	YY_BREAK
case 91:
YY_RULE_SETUP
#line 158 "D:\\win_flex_bison-latest\\code.l"
{ return PUNCTUATOR; }
	YY_BREAK
case 92:
YY_RULE_SETUP
#line 159 "D:\\win_flex_bison-latest\\code.l"
{ return PUNCTUATOR; }
	YY_BREAK
case 93:
YY_RULE_SETUP
#line 160 "D:\\win_flex_bison-latest\\code.l"
{ return PUNCTUATOR; }
	YY_BREAK
case 94:
YY_RULE_SETUP
#line 161 "D:\\win_flex_bison-latest\\code.l"
{ return PUNCTUATOR; }
	YY_BREAK
case 95:
YY_RULE_SETUP
#line 162 "D:\\win_flex_bison-latest\\code.l"
{ return PUNCTUATOR; }
	YY_BREAK
case 96:
YY_RULE_SETUP
#line 163 "D:\\win_flex_bison-latest\\code.l"
{ return PUNCTUATOR; }
	YY_BREAK
case 97:
YY_RULE_SETUP
#line 164 "D:\\win_flex_bison-latest\\code.l"
{ return PUNCTUATOR; }
	YY_BREAK
case 98:
YY_RULE_SETUP
#line 165 "D:\\win_flex_bison-latest\\code.l"
{ return PUNCTUATOR; }
	YY_BREAK
case 99:
YY_RULE_SETUP
#line 166 "D:\\win_flex_bison-latest\\code.l"
{ return PUNCTUATOR; }
	YY_BREAK
case 100:
YY_RULE_SETUP
#line 167 "D:\\win_flex_bison-latest\\code.l"
{ return PUNCTUATOR; }
	YY_BREAK
case 101:
YY_RULE_SETUP
#line 168 "D:\\win_flex_bison-latest\\code.l"
{ return PUNCTUATOR; }
	YY_BREAK
case 102:
YY_RULE_SETUP
#line 169 "D:\\win_flex_bison-latest\\code.l"
{ return PUNCTUATOR; }
	YY_BREAK
case 103:
YY_RULE_SETUP
#line 170 "D:\\win_flex_bison-latest\\code.l"
{ return PUNCTUATOR; }
	YY_BREAK
case 104:
YY_RULE_SETUP
#line 171 "D:\\win_flex_bison-latest\\code.l"
{ return PUNCTUATOR; }
	YY_BREAK
case 105:
YY_RULE_SETUP
#line 172 "D:\\win_flex_bison-latest\\code.l"
{ return PUNCTUATOR; }
	YY_BREAK
case 106:
YY_RULE_SETUP
#line 173 "D:\\win_flex_bison-latest\\code.l"
{ return PUNCTUATOR; }
	YY_BREAK
case 107:
YY_RULE_SETUP
#line 174 "D:\\win_flex_bison-latest\\code.l"
{ return PUNCTUATOR; }
	YY_BREAK
case 108:
YY_RULE_SETUP
#line 175 "D:\\win_flex_bison-latest\\code.l"
{ return PUNCTUATOR; }
	YY_BREAK
case 109:
YY_RULE_SETUP
#line 176 "D:\\win_flex_bison-latest\\code.l"
{ return PUNCTUATOR; }
	YY_BREAK
case 110:
YY_RULE_SETUP
#line 179 "D:\\win_flex_bison-latest\\code.l"
{ yyerror("illegal name"); return -1; } /* errors */
	YY_BREAK
case 111:
YY_RULE_SETUP
#line 180 "D:\\win_flex_bison-latest\\code.l"
{ yyerror("unclosed string"); return -1; }
	YY_BREAK
case 112:
YY_RULE_SETUP
#line 181 "D:\\win_flex_bison-latest\\code.l"
{ yyerror("unexpected character"); return -1; }
	YY_BREAK
case 113:
YY_RULE_SETUP
#line 183 "D:\\win_flex_bison-latest\\code.l"
ECHO;
	YY_BREAK
#line 1664 "D:\\win_flex_bison-latest\\code.yy.c"
case YY_STATE_EOF(INITIAL):
	yyterminate();

	case YY_END_OF_BUFFER:
		{
		/* Amount of text matched not including the EOB char. */
		int yy_amount_of_matched_text = (int) (yy_cp - (yytext_ptr)) - 1;

		/* Undo the effects of YY_DO_BEFORE_ACTION. */
		*yy_cp = (yy_hold_char);
		YY_RESTORE_YY_MORE_OFFSET

		if ( YY_CURRENT_BUFFER_LVALUE->yy_buffer_status == YY_BUFFER_NEW )
			{
			/* We're scanning a new file or input source.  It's
			 * possible that this happened because the user
			 * just pointed yyin at a new source and called
			 * yylex().  If so, then we have to assure
			 * consistency between YY_CURRENT_BUFFER and our
			 * globals.  Here is the right place to do so, because
			 * this is the first action (other than possibly a
			 * back-up) that will match for the new input source.
			 */
			(yy_n_chars) = YY_CURRENT_BUFFER_LVALUE->yy_n_chars;
			YY_CURRENT_BUFFER_LVALUE->yy_input_file = yyin;
			YY_CURRENT_BUFFER_LVALUE->yy_buffer_status = YY_BUFFER_NORMAL;
			}

		/* Note that here we test for yy_c_buf_p "<=" to the position
		 * of the first EOB in the buffer, since yy_c_buf_p will
		 * already have been incremented past the NUL character
		 * (since all states make transitions on EOB to the
		 * end-of-buffer state).  Contrast this with the test
		 * in input().
		 */
		if ( (yy_c_buf_p) <= &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] )
			{ /* This was really a NUL. */
			yy_state_type yy_next_state;

			(yy_c_buf_p) = (yytext_ptr) + yy_amount_of_matched_text;

			yy_current_state = yy_get_previous_state(  );

			/* Okay, we're now positioned to make the NUL
			 * transition.  We couldn't have
			 * yy_get_previous_state() go ahead and do it
			 * for us because it doesn't know how to deal
			 * with the possibility of jamming (and we don't
			 * want to build jamming into it because then it
			 * will run more slowly).
			 */

			yy_next_state = yy_try_NUL_trans( yy_current_state );

			yy_bp = (yytext_ptr) + YY_MORE_ADJ;

			if ( yy_next_state )
				{
				/* Consume the NUL. */
				yy_cp = ++(yy_c_buf_p);
				yy_current_state = yy_next_state;
				goto yy_match;
				}

			else
				{
				yy_cp = (yy_c_buf_p);
				goto yy_find_action;
				}
			}

		else switch ( yy_get_next_buffer(  ) )
			{
			case EOB_ACT_END_OF_FILE:
				{
				(yy_did_buffer_switch_on_eof) = 0;

				if ( yywrap(  ) )
					{
					/* Note: because we've taken care in
					 * yy_get_next_buffer() to have set up
					 * yytext, we can now set up
					 * yy_c_buf_p so that if some total
					 * hoser (like flex itself) wants to
					 * call the scanner after we return the
					 * YY_NULL, it'll still work - another
					 * YY_NULL will get returned.
					 */
					(yy_c_buf_p) = (yytext_ptr) + YY_MORE_ADJ;

					yy_act = YY_STATE_EOF(YY_START);
					goto do_action;
					}

				else
					{
					if ( ! (yy_did_buffer_switch_on_eof) )
						YY_NEW_FILE;
					}
				break;
				}

			case EOB_ACT_CONTINUE_SCAN:
				(yy_c_buf_p) =
					(yytext_ptr) + yy_amount_of_matched_text;

				yy_current_state = yy_get_previous_state(  );

				yy_cp = (yy_c_buf_p);
				yy_bp = (yytext_ptr) + YY_MORE_ADJ;
				goto yy_match;

			case EOB_ACT_LAST_MATCH:
				(yy_c_buf_p) =
				&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)];

				yy_current_state = yy_get_previous_state(  );

				yy_cp = (yy_c_buf_p);
				yy_bp = (yytext_ptr) + YY_MORE_ADJ;
				goto yy_find_action;
			}
		break;
		}

	default:
		YY_FATAL_ERROR(
			"fatal flex scanner internal error--no action found" );
	} /* end of action switch */
		} /* end of scanning one token */
	} /* end of user's declarations */
} /* end of yylex */

/* yy_get_next_buffer - try to read in a new buffer
 *
 * Returns a code representing an action:
 *	EOB_ACT_LAST_MATCH -
 *	EOB_ACT_CONTINUE_SCAN - continue scanning from current position
 *	EOB_ACT_END_OF_FILE - end of file
 */
static int yy_get_next_buffer (void)
{
    	char *dest = YY_CURRENT_BUFFER_LVALUE->yy_ch_buf;
	char *source = (yytext_ptr);
	int number_to_move, i;
	int ret_val;

	if ( (yy_c_buf_p) > &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars) + 1] )
		YY_FATAL_ERROR(
		"fatal flex scanner internal error--end of buffer missed" );

	if ( YY_CURRENT_BUFFER_LVALUE->yy_fill_buffer == 0 )
		{ /* Don't try to fill the buffer, so this is an EOF. */
		if ( (yy_c_buf_p) - (yytext_ptr) - YY_MORE_ADJ == 1 )
			{
			/* We matched a single character, the EOB, so
			 * treat this as a final EOF.
			 */
			return EOB_ACT_END_OF_FILE;
			}

		else
			{
			/* We matched some text prior to the EOB, first
			 * process it.
			 */
			return EOB_ACT_LAST_MATCH;
			}
		}

	/* Try to read more data. */

	/* First move last chars to start of buffer. */
	number_to_move = (int) ((yy_c_buf_p) - (yytext_ptr) - 1);

	for ( i = 0; i < number_to_move; ++i )
		*(dest++) = *(source++);

	if ( YY_CURRENT_BUFFER_LVALUE->yy_buffer_status == YY_BUFFER_EOF_PENDING )
		/* don't do the read, it's not guaranteed to return an EOF,
		 * just force an EOF
		 */
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars) = 0;

	else
		{
			int num_to_read =
			YY_CURRENT_BUFFER_LVALUE->yy_buf_size - number_to_move - 1;

		while ( num_to_read <= 0 )
			{ /* Not enough room in the buffer - grow it. */

			/* just a shorter name for the current buffer */
			YY_BUFFER_STATE b = YY_CURRENT_BUFFER_LVALUE;

			int yy_c_buf_p_offset =
				(int) ((yy_c_buf_p) - b->yy_ch_buf);

			if ( b->yy_is_our_buffer )
				{
				int new_size = b->yy_buf_size * 2;

				if ( new_size <= 0 )
					b->yy_buf_size += b->yy_buf_size / 8;
				else
					b->yy_buf_size *= 2;

				b->yy_ch_buf = (char *)
					/* Include room in for 2 EOB chars. */
					yyrealloc( (void *) b->yy_ch_buf,
							 (yy_size_t) (b->yy_buf_size + 2)  );
				}
			else
				/* Can't grow it, we don't own it. */
				b->yy_ch_buf = NULL;

			if ( ! b->yy_ch_buf )
				YY_FATAL_ERROR(
				"fatal error - scanner input buffer overflow" );

			(yy_c_buf_p) = &b->yy_ch_buf[yy_c_buf_p_offset];

			num_to_read = YY_CURRENT_BUFFER_LVALUE->yy_buf_size -
						number_to_move - 1;

			}

		if ( num_to_read > YY_READ_BUF_SIZE )
			num_to_read = YY_READ_BUF_SIZE;

		/* Read in more data. */
		YY_INPUT( (&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[number_to_move]),
			(yy_n_chars), num_to_read );

		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	if ( (yy_n_chars) == 0 )
		{
		if ( number_to_move == YY_MORE_ADJ )
			{
			ret_val = EOB_ACT_END_OF_FILE;
			yyrestart( yyin  );
			}

		else
			{
			ret_val = EOB_ACT_LAST_MATCH;
			YY_CURRENT_BUFFER_LVALUE->yy_buffer_status =
				YY_BUFFER_EOF_PENDING;
			}
		}

	else
		ret_val = EOB_ACT_CONTINUE_SCAN;

	if (((yy_n_chars) + number_to_move) > YY_CURRENT_BUFFER_LVALUE->yy_buf_size) {
		/* Extend the array by 50%, plus the number we really need. */
		int new_size = (yy_n_chars) + number_to_move + ((yy_n_chars) >> 1);
		YY_CURRENT_BUFFER_LVALUE->yy_ch_buf = (char *) yyrealloc(
			(void *) YY_CURRENT_BUFFER_LVALUE->yy_ch_buf, (yy_size_t) new_size  );
		if ( ! YY_CURRENT_BUFFER_LVALUE->yy_ch_buf )
			YY_FATAL_ERROR( "out of dynamic memory in yy_get_next_buffer()" );
		/* "- 2" to take care of EOB's */
		YY_CURRENT_BUFFER_LVALUE->yy_buf_size = (int) (new_size - 2);
	}

	(yy_n_chars) += number_to_move;
	YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] = YY_END_OF_BUFFER_CHAR;
	YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars) + 1] = YY_END_OF_BUFFER_CHAR;

	(yytext_ptr) = &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[0];

	return ret_val;
}

/* yy_get_previous_state - get the state just before the EOB char was reached */

    static yy_state_type yy_get_previous_state (void)
{
	yy_state_type yy_current_state;
	char *yy_cp;
    
	yy_current_state = (yy_start);

	for ( yy_cp = (yytext_ptr) + YY_MORE_ADJ; yy_cp < (yy_c_buf_p); ++yy_cp )
		{
		YY_CHAR yy_c = (*yy_cp ? yy_ec[YY_SC_TO_UI(*yy_cp)] : 1);
		if ( yy_accept[yy_current_state] )
			{
			(yy_last_accepting_state) = yy_current_state;
			(yy_last_accepting_cpos) = yy_cp;
			}
		while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
			{
			yy_current_state = (int) yy_def[yy_current_state];
			if ( yy_current_state >= 416 )
				yy_c = yy_meta[yy_c];
			}
		yy_current_state = yy_nxt[yy_base[yy_current_state] + yy_c];
		}

	return yy_current_state;
}

/* yy_try_NUL_trans - try to make a transition on the NUL character
 *
 * synopsis
 *	next_state = yy_try_NUL_trans( current_state );
 */
    static yy_state_type yy_try_NUL_trans  (yy_state_type yy_current_state )
{
	int yy_is_jam;
    	char *yy_cp = (yy_c_buf_p);

	YY_CHAR yy_c = 1;
	if ( yy_accept[yy_current_state] )
		{
		(yy_last_accepting_state) = yy_current_state;
		(yy_last_accepting_cpos) = yy_cp;
		}
	while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
		{
		yy_current_state = (int) yy_def[yy_current_state];
		if ( yy_current_state >= 416 )
			yy_c = yy_meta[yy_c];
		}
	yy_current_state = yy_nxt[yy_base[yy_current_state] + yy_c];
	yy_is_jam = (yy_current_state == 415);

		return yy_is_jam ? 0 : yy_current_state;
}

#ifndef YY_NO_UNPUT

    static void yyunput (int c, char * yy_bp )
{
	char *yy_cp;
    
    yy_cp = (yy_c_buf_p);

	/* undo effects of setting up yytext */
	*yy_cp = (yy_hold_char);

	if ( yy_cp < YY_CURRENT_BUFFER_LVALUE->yy_ch_buf + 2 )
		{ /* need to shift things up to make room */
		/* +2 for EOB chars. */
		int number_to_move = (yy_n_chars) + 2;
		char *dest = &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[
					YY_CURRENT_BUFFER_LVALUE->yy_buf_size + 2];
		char *source =
				&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[number_to_move];

		while ( source > YY_CURRENT_BUFFER_LVALUE->yy_ch_buf )
			*--dest = *--source;

		yy_cp += (int) (dest - source);
		yy_bp += (int) (dest - source);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars =
			(yy_n_chars) = (int) YY_CURRENT_BUFFER_LVALUE->yy_buf_size;

		if ( yy_cp < YY_CURRENT_BUFFER_LVALUE->yy_ch_buf + 2 )
			YY_FATAL_ERROR( "flex scanner push-back overflow" );
		}

	*--yy_cp = (char) c;

	(yytext_ptr) = yy_bp;
	(yy_hold_char) = *yy_cp;
	(yy_c_buf_p) = yy_cp;
}

#endif

#ifndef YY_NO_INPUT
#ifdef __cplusplus
    static int yyinput (void)
#else
    static int input  (void)
#endif

{
	int c;
    
	*(yy_c_buf_p) = (yy_hold_char);

	if ( *(yy_c_buf_p) == YY_END_OF_BUFFER_CHAR )
		{
		/* yy_c_buf_p now points to the character we want to return.
		 * If this occurs *before* the EOB characters, then it's a
		 * valid NUL; if not, then we've hit the end of the buffer.
		 */
		if ( (yy_c_buf_p) < &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] )
			/* This was really a NUL. */
			*(yy_c_buf_p) = '\0';

		else
			{ /* need more input */
			int offset = (int) ((yy_c_buf_p) - (yytext_ptr));
			++(yy_c_buf_p);

			switch ( yy_get_next_buffer(  ) )
				{
				case EOB_ACT_LAST_MATCH:
					/* This happens because yy_g_n_b()
					 * sees that we've accumulated a
					 * token and flags that we need to
					 * try matching the token before
					 * proceeding.  But for input(),
					 * there's no matching to consider.
					 * So convert the EOB_ACT_LAST_MATCH
					 * to EOB_ACT_END_OF_FILE.
					 */

					/* Reset buffer status. */
					yyrestart( yyin );

					/*FALLTHROUGH*/

				case EOB_ACT_END_OF_FILE:
					{
					if ( yywrap(  ) )
						return 0;

					if ( ! (yy_did_buffer_switch_on_eof) )
						YY_NEW_FILE;
#ifdef __cplusplus
					return yyinput();
#else
					return input();
#endif
					}

				case EOB_ACT_CONTINUE_SCAN:
					(yy_c_buf_p) = (yytext_ptr) + offset;
					break;
				}
			}
		}

	c = *(unsigned char *) (yy_c_buf_p);	/* cast for 8-bit char's */
	*(yy_c_buf_p) = '\0';	/* preserve yytext */
	(yy_hold_char) = *++(yy_c_buf_p);

	return c;
}
#endif	/* ifndef YY_NO_INPUT */

/** Immediately switch to a different input stream.
 * @param input_file A readable stream.
 * 
 * @note This function does not reset the start condition to @c INITIAL .
 */
    void yyrestart  (FILE * input_file )
{
    
	if ( ! YY_CURRENT_BUFFER ){
        yyensure_buffer_stack ();
		YY_CURRENT_BUFFER_LVALUE =
            yy_create_buffer( yyin, YY_BUF_SIZE );
	}

	yy_init_buffer( YY_CURRENT_BUFFER, input_file );
	yy_load_buffer_state(  );
}

/** Switch to a different input buffer.
 * @param new_buffer The new input buffer.
 * 
 */
    void yy_switch_to_buffer  (YY_BUFFER_STATE  new_buffer )
{
    
	/* TODO. We should be able to replace this entire function body
	 * with
	 *		yypop_buffer_state();
	 *		yypush_buffer_state(new_buffer);
     */
	yyensure_buffer_stack ();
	if ( YY_CURRENT_BUFFER == new_buffer )
		return;

	if ( YY_CURRENT_BUFFER )
		{
		/* Flush out information for old buffer. */
		*(yy_c_buf_p) = (yy_hold_char);
		YY_CURRENT_BUFFER_LVALUE->yy_buf_pos = (yy_c_buf_p);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	YY_CURRENT_BUFFER_LVALUE = new_buffer;
	yy_load_buffer_state(  );

	/* We don't actually know whether we did this switch during
	 * EOF (yywrap()) processing, but the only time this flag
	 * is looked at is after yywrap() is called, so it's safe
	 * to go ahead and always set it.
	 */
	(yy_did_buffer_switch_on_eof) = 1;
}

static void yy_load_buffer_state  (void)
{
    	(yy_n_chars) = YY_CURRENT_BUFFER_LVALUE->yy_n_chars;
	(yytext_ptr) = (yy_c_buf_p) = YY_CURRENT_BUFFER_LVALUE->yy_buf_pos;
	yyin = YY_CURRENT_BUFFER_LVALUE->yy_input_file;
	(yy_hold_char) = *(yy_c_buf_p);
}

/** Allocate and initialize an input buffer state.
 * @param file A readable stream.
 * @param size The character buffer size in bytes. When in doubt, use @c YY_BUF_SIZE.
 * 
 * @return the allocated buffer state.
 */
    YY_BUFFER_STATE yy_create_buffer  (FILE * file, int  size )
{
	YY_BUFFER_STATE b;
    
	b = (YY_BUFFER_STATE) yyalloc( sizeof( struct yy_buffer_state )  );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_buf_size = size;

	/* yy_ch_buf has to be 2 characters longer than the size given because
	 * we need to put in 2 end-of-buffer characters.
	 */
	b->yy_ch_buf = (char *) yyalloc( (yy_size_t) (b->yy_buf_size + 2)  );
	if ( ! b->yy_ch_buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_is_our_buffer = 1;

	yy_init_buffer( b, file );

	return b;
}

/** Destroy the buffer.
 * @param b a buffer created with yy_create_buffer()
 * 
 */
    void yy_delete_buffer (YY_BUFFER_STATE  b )
{
    
	if ( ! b )
		return;

	if ( b == YY_CURRENT_BUFFER ) /* Not sure if we should pop here. */
		YY_CURRENT_BUFFER_LVALUE = (YY_BUFFER_STATE) 0;

	if ( b->yy_is_our_buffer )
		yyfree( (void *) b->yy_ch_buf  );

	yyfree( (void *) b  );
}

/* Initializes or reinitializes a buffer.
 * This function is sometimes called more than once on the same buffer,
 * such as during a yyrestart() or at EOF.
 */
    static void yy_init_buffer  (YY_BUFFER_STATE  b, FILE * file )

{
	int oerrno = errno;
    
	yy_flush_buffer( b );

	b->yy_input_file = file;
	b->yy_fill_buffer = 1;

    /* If b is the current buffer, then yy_init_buffer was _probably_
     * called from yyrestart() or through yy_get_next_buffer.
     * In that case, we don't want to reset the lineno or column.
     */
    if (b != YY_CURRENT_BUFFER){
        b->yy_bs_lineno = 1;
        b->yy_bs_column = 0;
    }

        b->yy_is_interactive = file ? (isatty( fileno(file) ) > 0) : 0;
    
	errno = oerrno;
}

/** Discard all buffered characters. On the next scan, YY_INPUT will be called.
 * @param b the buffer state to be flushed, usually @c YY_CURRENT_BUFFER.
 * 
 */
    void yy_flush_buffer (YY_BUFFER_STATE  b )
{
    	if ( ! b )
		return;

	b->yy_n_chars = 0;

	/* We always need two end-of-buffer characters.  The first causes
	 * a transition to the end-of-buffer state.  The second causes
	 * a jam in that state.
	 */
	b->yy_ch_buf[0] = YY_END_OF_BUFFER_CHAR;
	b->yy_ch_buf[1] = YY_END_OF_BUFFER_CHAR;

	b->yy_buf_pos = &b->yy_ch_buf[0];

	b->yy_at_bol = 1;
	b->yy_buffer_status = YY_BUFFER_NEW;

	if ( b == YY_CURRENT_BUFFER )
		yy_load_buffer_state(  );
}

/** Pushes the new state onto the stack. The new state becomes
 *  the current state. This function will allocate the stack
 *  if necessary.
 *  @param new_buffer The new state.
 *  
 */
void yypush_buffer_state (YY_BUFFER_STATE new_buffer )
{
    	if (new_buffer == NULL)
		return;

	yyensure_buffer_stack();

	/* This block is copied from yy_switch_to_buffer. */
	if ( YY_CURRENT_BUFFER )
		{
		/* Flush out information for old buffer. */
		*(yy_c_buf_p) = (yy_hold_char);
		YY_CURRENT_BUFFER_LVALUE->yy_buf_pos = (yy_c_buf_p);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	/* Only push if top exists. Otherwise, replace top. */
	if (YY_CURRENT_BUFFER)
		(yy_buffer_stack_top)++;
	YY_CURRENT_BUFFER_LVALUE = new_buffer;

	/* copied from yy_switch_to_buffer. */
	yy_load_buffer_state(  );
	(yy_did_buffer_switch_on_eof) = 1;
}

/** Removes and deletes the top of the stack, if present.
 *  The next element becomes the new top.
 *  
 */
void yypop_buffer_state (void)
{
    	if (!YY_CURRENT_BUFFER)
		return;

	yy_delete_buffer(YY_CURRENT_BUFFER );
	YY_CURRENT_BUFFER_LVALUE = NULL;
	if ((yy_buffer_stack_top) > 0)
		--(yy_buffer_stack_top);

	if (YY_CURRENT_BUFFER) {
		yy_load_buffer_state(  );
		(yy_did_buffer_switch_on_eof) = 1;
	}
}

/* Allocates the stack if it does not exist.
 *  Guarantees space for at least one push.
 */
static void yyensure_buffer_stack (void)
{
	yy_size_t num_to_alloc;
    
	if (!(yy_buffer_stack)) {

		/* First allocation is just for 2 elements, since we don't know if this
		 * scanner will even need a stack. We use 2 instead of 1 to avoid an
		 * immediate realloc on the next call.
         */
      num_to_alloc = 1; /* After all that talk, this was set to 1 anyways... */
		(yy_buffer_stack) = (struct yy_buffer_state**)yyalloc
								(num_to_alloc * sizeof(struct yy_buffer_state*)
								);
		if ( ! (yy_buffer_stack) )
			YY_FATAL_ERROR( "out of dynamic memory in yyensure_buffer_stack()" );

		memset((yy_buffer_stack), 0, num_to_alloc * sizeof(struct yy_buffer_state*));

		(yy_buffer_stack_max) = num_to_alloc;
		(yy_buffer_stack_top) = 0;
		return;
	}

	if ((yy_buffer_stack_top) >= ((yy_buffer_stack_max)) - 1){

		/* Increase the buffer to prepare for a possible push. */
		yy_size_t grow_size = 8 /* arbitrary grow size */;

		num_to_alloc = (yy_buffer_stack_max) + grow_size;
		(yy_buffer_stack) = (struct yy_buffer_state**)yyrealloc
								((yy_buffer_stack),
								num_to_alloc * sizeof(struct yy_buffer_state*)
								);
		if ( ! (yy_buffer_stack) )
			YY_FATAL_ERROR( "out of dynamic memory in yyensure_buffer_stack()" );

		/* zero only the new slots.*/
		memset((yy_buffer_stack) + (yy_buffer_stack_max), 0, grow_size * sizeof(struct yy_buffer_state*));
		(yy_buffer_stack_max) = num_to_alloc;
	}
}

/** Setup the input buffer state to scan directly from a user-specified character buffer.
 * @param base the character buffer
 * @param size the size in bytes of the character buffer
 * 
 * @return the newly allocated buffer state object.
 */
YY_BUFFER_STATE yy_scan_buffer  (char * base, yy_size_t  size )
{
	YY_BUFFER_STATE b;
    
	if ( size < 2 ||
	     base[size-2] != YY_END_OF_BUFFER_CHAR ||
	     base[size-1] != YY_END_OF_BUFFER_CHAR )
		/* They forgot to leave room for the EOB's. */
		return NULL;

	b = (YY_BUFFER_STATE) yyalloc( sizeof( struct yy_buffer_state )  );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_buffer()" );

	b->yy_buf_size = (int) (size - 2);	/* "- 2" to take care of EOB's */
	b->yy_buf_pos = b->yy_ch_buf = base;
	b->yy_is_our_buffer = 0;
	b->yy_input_file = NULL;
	b->yy_n_chars = b->yy_buf_size;
	b->yy_is_interactive = 0;
	b->yy_at_bol = 1;
	b->yy_fill_buffer = 0;
	b->yy_buffer_status = YY_BUFFER_NEW;

	yy_switch_to_buffer( b  );

	return b;
}

/** Setup the input buffer state to scan a string. The next call to yylex() will
 * scan from a @e copy of @a str.
 * @param yystr a NUL-terminated string to scan
 * 
 * @return the newly allocated buffer state object.
 * @note If you want to scan bytes that may contain NUL values, then use
 *       yy_scan_bytes() instead.
 */
YY_BUFFER_STATE yy_scan_string (const char * yystr )
{
    
	return yy_scan_bytes( yystr, (int) strlen(yystr) );
}

/** Setup the input buffer state to scan the given bytes. The next call to yylex() will
 * scan from a @e copy of @a bytes.
 * @param yybytes the byte buffer to scan
 * @param _yybytes_len the number of bytes in the buffer pointed to by @a bytes.
 * 
 * @return the newly allocated buffer state object.
 */
YY_BUFFER_STATE yy_scan_bytes  (const char * yybytes, int  _yybytes_len )
{
	YY_BUFFER_STATE b;
	char *buf;
	yy_size_t n;
	int i;
    
	/* Get memory for full buffer, including space for trailing EOB's. */
	n = (yy_size_t) (_yybytes_len + 2);
	buf = (char *) yyalloc( n  );
	if ( ! buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_bytes()" );

	for ( i = 0; i < _yybytes_len; ++i )
		buf[i] = yybytes[i];

	buf[_yybytes_len] = buf[_yybytes_len+1] = YY_END_OF_BUFFER_CHAR;

	b = yy_scan_buffer( buf, n );
	if ( ! b )
		YY_FATAL_ERROR( "bad buffer in yy_scan_bytes()" );

	/* It's okay to grow etc. this buffer, and we should throw it
	 * away when we're done.
	 */
	b->yy_is_our_buffer = 1;

	return b;
}

#ifndef YY_EXIT_FAILURE
#define YY_EXIT_FAILURE 2
#endif

static void yynoreturn yy_fatal_error (const char* msg )
{
			fprintf( stderr, "%s\n", msg );
	exit( YY_EXIT_FAILURE );
}

/* Redefine yyless() so it works in section 3 code. */

#undef yyless
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
        int yyless_macro_arg = (n); \
        YY_LESS_LINENO(yyless_macro_arg);\
		yytext[yyleng] = (yy_hold_char); \
		(yy_c_buf_p) = yytext + yyless_macro_arg; \
		(yy_hold_char) = *(yy_c_buf_p); \
		*(yy_c_buf_p) = '\0'; \
		yyleng = yyless_macro_arg; \
		} \
	while ( 0 )

/* Accessor  methods (get/set functions) to struct members. */

/** Get the current line number.
 * 
 */
int yyget_lineno  (void)
{
    
    return yylineno;
}

/** Get the input stream.
 * 
 */
FILE *yyget_in  (void)
{
        return yyin;
}

/** Get the output stream.
 * 
 */
FILE *yyget_out  (void)
{
        return yyout;
}

/** Get the length of the current token.
 * 
 */
int yyget_leng  (void)
{
        return yyleng;
}

/** Get the current token.
 * 
 */

char *yyget_text  (void)
{
        return yytext;
}

/** Set the current line number.
 * @param _line_number line number
 * 
 */
void yyset_lineno (int  _line_number )
{
    
    yylineno = _line_number;
}

/** Set the input stream. This does not discard the current
 * input buffer.
 * @param _in_str A readable stream.
 * 
 * @see yy_switch_to_buffer
 */
void yyset_in (FILE *  _in_str )
{
        yyin = _in_str ;
}

void yyset_out (FILE *  _out_str )
{
        yyout = _out_str ;
}

int yyget_debug  (void)
{
        return yy_flex_debug;
}

void yyset_debug (int  _bdebug )
{
        yy_flex_debug = _bdebug ;
}

static int yy_init_globals (void)
{
        /* Initialization is the same as for the non-reentrant scanner.
     * This function is called from yylex_destroy(), so don't allocate here.
     */

    (yy_buffer_stack) = NULL;
    (yy_buffer_stack_top) = 0;
    (yy_buffer_stack_max) = 0;
    (yy_c_buf_p) = NULL;
    (yy_init) = 0;
    (yy_start) = 0;

/* Defined in main.c */
#ifdef YY_STDINIT
    yyin = stdin;
    yyout = stdout;
#else
    yyin = NULL;
    yyout = NULL;
#endif

    /* For future reference: Set errno on error, since we are called by
     * yylex_init()
     */
    return 0;
}

/* yylex_destroy is for both reentrant and non-reentrant scanners. */
int yylex_destroy  (void)
{
    
    /* Pop the buffer stack, destroying each element. */
	while(YY_CURRENT_BUFFER){
		yy_delete_buffer( YY_CURRENT_BUFFER  );
		YY_CURRENT_BUFFER_LVALUE = NULL;
		yypop_buffer_state();
	}

	/* Destroy the stack itself. */
	yyfree((yy_buffer_stack) );
	(yy_buffer_stack) = NULL;

    /* Reset the globals. This is important in a non-reentrant scanner so the next time
     * yylex() is called, initialization will occur. */
    yy_init_globals( );

    return 0;
}

/*
 * Internal utility routines.
 */

#ifndef yytext_ptr
static void yy_flex_strncpy (char* s1, const char * s2, int n )
{
		
	int i;
	for ( i = 0; i < n; ++i )
		s1[i] = s2[i];
}
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen (const char * s )
{
	int n;
	for ( n = 0; s[n]; ++n )
		;

	return n;
}
#endif

void *yyalloc (yy_size_t  size )
{
			return malloc(size);
}

void *yyrealloc  (void * ptr, yy_size_t  size )
{
		
	/* The cast to (char *) in the following accommodates both
	 * implementations that use char* generic pointers, and those
	 * that use void* generic pointers.  It works with the latter
	 * because both ANSI C and C++ allow castless assignment from
	 * any pointer type to void*, and deal with argument conversions
	 * as though doing an assignment.
	 */
	return realloc(ptr, size);
}

void yyfree (void * ptr )
{
			free( (char *) ptr );	/* see yyrealloc() for (char *) cast */
}

#define YYTABLES_NAME "yytables"

#line 183 "D:\\win_flex_bison-latest\\code.l"


void yyerror(const char *err)
{
    errorCount++;
    fprintf(stderr, "%d:%d:[\033[31mError: \033[32m%s\033[39m]: %s\n", lineCount, columnCount, err, yytext);
}

static void isComment(void)
{
    int c;

    while ((c = yyinput()) != 0)
    {
        charCount++;
        if (c == '\n')
            lineCount++;
        if (c == '*')
        {
            while ((c = yyinput()) == '*')
            {
                charCount++;
            }
            charCount++;
            if (c == '\n')
            {
                lineCount++;
                columnCount = 1;
            }

            if (c == '/')
            {
                return;
            }

            if (c == 0)
                break;
        }
    }
    yyerror("unterminated comment");
}

int main()
{
    int code;
    yyin = fopen("D:\\program\\work\\code\\test\\test2.c", "r");

    while ((code = yylex()))    // code is the type of token
    {
        charCount += yyleng;    // character counts
        switch (code)
        {
        case KEYWORD:
            keywordCount++;
            printf("%d:%d: [Keyword]: %s\n", lineCount, columnCount, yytext);
            break;
        case IDENTIFIER:
            identifierCount++;
            printf("%d:%d: [Identifier]: %s\n", lineCount, columnCount, yytext);
            break;
        case I_CONSTANT:
            integerConst++;
            printf("%d:%d: [Integer]: %s\n", lineCount, columnCount, yytext);
            break;
        case C_CONSTANT:
            charConst++;
            printf("%d:%d: [Character]: %s\n", lineCount, columnCount, yytext);
            break;
        case F_CONSTANT:
            floatingConst++;
            printf("%d:%d: [Floating]: %s\n", lineCount, columnCount, yytext);
            break;
        case STRING_LITERAL:
            stringCount++;
            printf("%d:%d: [String]: %s\n", lineCount, columnCount, yytext);
            break;
        case PUNCTUATOR:
            punctuatorCount++;
            printf("%d:%d: [Punctuator]: %s\n", lineCount, columnCount, yytext);
            break;
        default:
            break;
        }
        columnCount += yyleng;  // cursor forward
    }
    printf("\nTotal characters:\t%d\n", charCount);
    printf("Total lines:\t%d\n", lineCount);
    printf("\n");
    printf("Keyword:\t%d\n", keywordCount);
    printf("Identifier:\t%d\n", identifierCount);
    printf("Integers:\t%d\n", integerConst);
    printf("Floatings:\t%d\n", floatingConst);
    printf("Characters:\t%d\n", charConst);
    printf("Strings:\t%d\n", stringCount);
    printf("Punctuators:\t%d\n", punctuatorCount);
    printf("\033[1mErrors:\t\t%d\n\033", errorCount);

    fclose(yyin);
    return 0;
}

/* 
 *D:\win_flex_bison-latest\win_flex.exe --wincompat --outfile=D:\win_flex_bison-latest\code.yy.c D:\win_flex_bison-latest\code.l
 */
