// VS Code C/C++ Test Code "Hello World"
// Generated by VSCodeConfigHelper v4.0.7

// You can create a .cpp source file in the current folder (workspace folder) to write your code.

// Press Ctrl + F5 to compile and run.
// Press F5 to compile and debug.
// Press Ctrl + Shift + B to compile.

#include <stdio.h>

int main() {
    // Print "Hello, world!" to the standard output
    printf("Hello, world!\n");
    return 0;
}

// This file will output "Hello, world!" when compiled and executed.
// After pressing Ctrl + F5, you will see this line in the popped terminal window.
// !! Important Note: Please make sure the file name does not contain Chinese or special characters before writing code. !!
// If you encounter any issues, please contact the developer at guyutongxue@163.com.